# -*- coding: utf-8 -*-

DEBUG=True

REDIS_HOST="192.168.33.10"
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD="123456"

MYSQL_HOST = "192.168.33.10"
MYSQL_PORT = 3306
MYSQL_AUTOCOMMIT = True
MYSQL_CHARSET = 'utf8'

MYSQL_USER = "root"
MYSQL_PASSWD = ""

MYSQL_DATABASE = "oa"

MYSQL = (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWD, MYSQL_DATABASE, MYSQL_AUTOCOMMIT, MYSQL_CHARSET)


#gobelieve
APP_ID = 1466
APP_SECRET = 'tCj084rJXwaFfKp7vpBhJmlomBsPmZON'

GOBELIEVE_URL = "https://api.gobelieve.io"

#云之讯账号
UC_ACCOUNT_SID = ""
UC_ACCOUNT_TOKEN = ""
UC_APPID = ""
UC_TEMPLATE_ID = ""
